### ISSUE TITLE
The app does not register dark/light mode properly

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka#20]
**Describe the bug** 🐛
Currently, the theme mostly stays identical regardless of what mode I have set on my system.

**To Reproduce** 📝
1. Open the app
2. Switch between light and dark on your system (how you do it varies between operating systems)
3. Notice that nothing changes in the app theme.

**Expected behavior** 🕵️‍♂️
I expect the theme to be a lighter tone when my system is set to light mode,
but then switch to a darker theme, when my system is in dark mode.

**Screenshots** 🖼

__Dark Mode__:
<img width="1912" alt="image" src="https://github.com/flowcore-io/open-source-conference-app/assets/3743913/0a06868c-254f-47fa-ba3c-a58aa6f53522">

__Light Mode__:
<img width="1912" alt="image" src="https://github.com/flowcore-io/open-source-conference-app/assets/3743913/b93484ed-07a3-4c4b-aedf-7128a6283c17">

**Additional Information (optional)**
***Where it occurred***
- Desktop
  - OS: Mac OS - Sonoma 14.1.1
  - Browser: Arc 1.30.0

***Additional context***
Ideally, the solution would adhere to css variables, to future proof the ability to change the theme programatically, if needed

**Comment by Fjandin** [comment]
Partially  fixed with https://github.com/flowcore-io/luttaka/pull/79

For now it always defaults to `light` mode since the `dark` mode styling is not done
