### ISSUE TITLE
The app requires a minimum version of node to run

### ISSUE THREAD

**Issue by suuunly** [flowcore-io/luttaka#77]
**Describe the bug** 🐛
When running `yarn install` I am presented with an error that my NodeJS is too old.
I am running node `v.20.1.0`

**To Reproduce** 📝
1. Run `yarn install`
2. Get an error in the terminal saying that my version is too old

**Expected behavior** 🕵️‍♂️
This should be documented in the `README`, to let people know what the minimum node version is required to run this application

**Additional Information (optional)**
***Where it occurred***
- Desktop
  - OS: Mac OS Sonoma 14.3.1
  
***Additional context***
I use `nvm`  and when I switched to node `v20.11.0`, it worked fine 😄

**Comment by themujahidkhan** [comment]
I would like to work on this, 

Do you want me to include the node minimum version in the **prerequisite** section or the **Run Locally** section?

**Comment by suuunly** [comment]
@themujahidkhan, excellent :)
you can put it in the prerequisite. As it will most likely grow over time 😄

**Comment by themujahidkhan** [comment]
Thanks @suuunly 

What do you think about this iteration?

![image](https://github.com/flowcore-io/luttaka/assets/72564155/6e9270a8-73b6-4132-8814-b3ceddae5dd5)

Or Should I come up with a different copy?

**Comment by suuunly** [comment]
Mostly, I am thinking that if people are interested in using nvm, then they can press the link and read nvm's guide 😄 
That way we don't need to maintain the nvm documentation on our end, in case things change on their end 😁

**Comment by themujahidkhan** [comment]
How about now?

**Updated Content Screenshot**

![image](https://github.com/flowcore-io/luttaka/assets/72564155/e50e5d67-eaca-488a-b3d8-480e43e992b9)

**Comment by themujahidkhan** [comment]
Let me know if that works, I'll open a PR

**Comment by suuunly** [comment]
That looks good 😁😁👌🏻

**Comment by themujahidkhan** [comment]
Done PR created
